name: "Test"
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - name: Add keys group (needed for go tests)
      run: sudo groupadd keys
    - name: Run unit tests
      run: nix develop .#unit-tests --command "true"
